fix doc
JuliaDiff/ChainRulesTestUtils.jl pull request #126
Opened 2021-03-14 10:58 UTC by ho-oto

2021-03-14 11:06 UTC, willtebbutt approved these changes
Thanks for catching this!

2021-03-14 11:11 UTC, willtebbutt requested changes
Actually, could you please bump the patch. Since this is a change to `src`, we'll issue a patch release.

2021-03-18 05:19 UTC, ho-oto commented
done!

2021-03-18 09:54 UTC, mzgubic approved these changes

2021-05-06 16:25 UTC, merged